MAPPINGS = {
	"address_title": "Address data",
	"uuid": "building id (uuid)",
	"voiv": "voivodship",
	"pov": "poviat",
	"mun": "municipality",
	"zip": "zipcode",
	"city": "city/locality",
	"city_district": "district or part",
	"prefix": "street prefix",
	"street": "street name based on DataWise standard",
	"gus_name": "street name based on MSO (GUS TERYT) standard",
	"current_street": "current street name (only if changed)",
	"building": "street/building number",
	"xy_title": "Geolocation",
	"y": "latitude",
	"x": "longitude",
	"xy_class": "latlon accuracy code",
	"xy_class_label": "latlon accuracy label (PL)",
	"add_info_title": "Additional address info",
	"mun_type": "typ gminy",
	"sym": "symbol miasta",
	"symd": "symbol dzielnicy",
	"mqg7d": "kod gminy",
	"msegm": "segment gminy",
	"mwg14": "numer kierunkowy",
	"eurogrid62": "kod eurogrid",
	"ctype": "typ miasta / lokalizacji",
	"symul": "kod ulicy",
	"btype": "typ budynku",
	"bneigh": "dominujący typ budynków w sąsiedztwie",
	"elev": "wysokość nad poziomem morza",
	"building_title": "Informacje o budynku",
	"gus_cech": "cecha ulicy w TERYT",
	"gus_naz1": "nazwa ulicy w TERYT - pierwszy człon",
	"gus_naz2": "nazwa ulicy w TERYT - drugi człon",
	"csize": "wielkość miejscowości - liczba ludności ",
	"agglom": "nazwa aglomeracji",
	"mwg7": "kod gminy TERYT w wersji bez podziału na dzielnice",
	"mwg7_version": "rok na jaki jest aktualny kod mwg7",
	"mwg14_version": "rok na jaki jest aktualny kod mwg14",
	"egr_0125": "kod siatki eurogrid 125m",
	"hex_0125": "kod siatki hex 125m",
	"poc_act": "liczba działalności CEIDG aktywne",
	"crc_tot": "liczba firm KRS RAZEM",
	"apts_t": "liczba lokali razem",
	"pop_apts": "szacowana liczba gospodarstw domowych",
	"pop_tot": "szacowana liczba mieszkańców razem",
	"popf_tot": "szacowana liczba mieszkańców-kobiety razem",
	"popm_tot": "szacowana liczba mieszkańców-mężczyźni razem",
	"popt0004": "szacowana liczba mieszkańców w wieku do 4 lat",
	"popt0509": "szacowana liczba mieszkańców w wieku od 5 do 9 lat",
	"popt1014": "szacowana liczba mieszkańców w wieku od 10 do 14 lat ",
	"popt1519": "szacowana liczba mieszkańców w wieku od 15 do 19 lat",
	"popt2024": "szacowana liczba mieszkańców w wieku od 20 do 24 lat",
	"popt2529": "szacowana liczba mieszkańców w wieku od 25 do 29 lat",
	"popt3034": "szacowana liczba mieszkańców w wieku od 30 do 34 lat",
	"popt3539": "szacowana liczba mieszkańców w wieku od 35 do 39 lat",
	"popt4044": "szacowana liczba mieszkańców w wieku od 40 do 44 lat",
	"popt4549": "szacowana liczba mieszkańców w wieku od 45 do 49 lat",
	"popt5054": "szacowana liczba mieszkańców w wieku od 50 do 54 lat",
	"popt5559": "szacowana liczba mieszkańców w wieku od 55 do 59 lat",
	"popt6064": "szacowana liczba mieszkańców w wieku od 60 do 64 lat",
	"popt6569": "szacowana liczba mieszkańców w wieku od 65 do 69 lat",
	"popt7074": "szacowana liczba mieszkańców w wieku od 70 do 74 lat",
	"popt7599": "szacowana liczba mieszkańców w wieku 75 i więcej lat",
	"pop_ax_t": "szacowany średni wiek mieszkańców razem",
	"pop_ax_y": "szacowany średni wiek mieszkańców - tylko osoby w wieku 15 i więcej lat",
	"inbld_t": "uśredniony na poziomie budynku miesięczny dochód netto - wszystkie osoby",
	"inbld_w": "uśredniony na poziomie budynku miesięczny dochód netto - osoby pracujące",
	"poi_szpital": "number o POI - category: SZPITAL",
	"poi_poczta": "number o POI - category: POCZTA",
	"poi_przedszkole": "number o POI - category: PRZEDSZKOLE",
	"poi_szk_podst": "number o POI - category: SZKOŁA PODSTAWOWA",
	"poi_szk_wyzsza": "number o POI - category: SZKOŁA WYŻSZA",
	"poi_bankomat": "number o POI - category: BANKOMAT",
	"poi_stacja_paliw": "number o POI - category: STACJA PALIW",
	"poi_centrala_banku": "number o POI - category: CENTRALA BANKU ",
	"poi_oddzial_banku": "number o POI - category: ODDZIAŁ BANKU",
	"poi_hipermarket": "number o POI - category: HANDEL-HIPERMARKET ",
	"poi_supermarket": "number o POI - category: HANDEL-SUPERMARKET ",
	"poi_dyskont": "number o POI - category: HANDEL-DYSKONT",
	"poi_convenience": "number o POI - category: HANDEL-CONVENIENCE ",
	"poi_drogeria": "number o POI - category: HANDEL-DROGERIA",
	"poi_multimedia": "number o POI - category: HANDEL-MULTIMEDIA",
	"poi_wyposazenie": "number o POI - category: HANDEL-WYPOSAŻENIE DOMU ",
	"poi_ch": "number o POI - category: CENTRUM HANDLOWE",
	"poi_urzad": "number o POI - category: URZĄD",
	"poi_ambasada": "number o POI - category: AMBASADA ",
	"poi_fast_food": "number o POI - category: FAST-FOOD",
	"poi_muzeum_kino": "number o POI - category: MUZEUM, KINO",
	"poi_apteka": "number o POI - category: APTEKA ",
	"poi_pkp": "number o POI - category: DWORZEC, STACJA PKP",
	"uke_version": "dane UKE wg stanu na dzień",
	"cpr": "dane UKE - liczba dostawców internetu ",
	"cpr_twi": "dane UKE - liczba dostawców drogą telefoniczną",
	"cpr_coa": "dane UKE - liczba dostawców drogą sieci telewizji kablowych",
	"cpr_fib": "dane UKE - liczba dostawców drogą światłowodową",
	"mbps": "dane UKE - maksymalna przepustowość w megabitach na sekundę",
	"mbps_twi": "dane UKE - maksymalna przepustowość w megabitach na sekundę drogą telefoniczną",
	"mbps_coa": "dane UKE - maksymalna przepustowość w megabitach na sekundę drogą sieci telewizji kablowych",
	"mbps_fib": "dane UKE - maksymalna przepustowość w megabitach na sekundę drogą światłowodową",
	"sfp_class": "szacowany okres zasiedlenia budynku",
	"bheight": "szacunkowa liczba pięter w budynku",
	"post": "poczta",
	"flat": "numer mieszkania",
	"strnum_all": "pełny numer ulicy (numer budynku, mieszkania)",
	"symp": "symbol poczty",
	"notes": "dodatkowe informacje",
	"symul_active": "czy ulica aktualnie istnieje",
	"current_symul": "aktualny kod ulicy",
	"current_prefix": "aktualny prefiks",
	"corner": "ulica narożna",
	"gus_prefix": "prefiks wg standardu GUS TERYT",
	"gus_street": "ulica wg standardu GUS TERYT",
	"mwg7d": "kod gminy z podziałem na dzielnice",
	"quality": "status",
	"loc_label": "Dane o lokalizacji",
	"label": "pełny adres zbudowany z przeanalizowanych komponentów adresu",
	"country": "kod kraju",
	"country_name": "nazwa kraju",
	"state": "pierwszy poziom administracyjny adresu",
	"location_id": "identyfikator lokalizacji",
	"location_type": "typ lokalizacji",
	"match_level": "poziom dopasowania",
	"match_type": "rodzaj dopasowania",
	"area_km2": "zasięg w km",
	"bld_t": "liczba budynków – suma",
	"bld_r": "liczba budynków - mieszkalnych",
	"apts_r": "liczba mieszkań - mieszkalnych według DataWise",
	"apts_rp": "liczba mieszkań - mieszkalnych w rejestrze publicznym",
	"hh_size": "średnia liczba osób na gospodarstwo domowe",
	"pop_den": "gęstość zaludnienia osób na km2",
	"pprf": "populacja - procent kobiet",
	"pprm": "populacja - procent mężczyzn",
	"ppr0004": "przykład: 4.13",
	"ppr0509": "populacja - procentowe kategorie wiekowe od 5 do 9 lat",
	"ppr1014": "populacja - kategorie wiekowe od 10 do 14 lat",
	"ppr1519": "populacja - procentowe kategorie wiekowe od 15 do 19 lat",
	"ppr2024": "populacja - procentowe kategorie wiekowe od 20 do 24 lat",
	"ppr2529": "populacja - procentowe kategorie wiekowe od 25 do 29 lat",
	"ppr3034": "populacja - procentowe kategorie wiekowe od 30 do 34 lat",
	"ppr3539": "populacja - kategorie wiekowe od 35 do 39 lat",
	"ppr4044": "populacja - procentowe kategorie wiekowe od 40 do 44 lat",
	"ppr4549": "populacja - procentowe kategorie wiekowe od 45 do 49 lat",
	"ppr5054": "populacja - procentowe kategorie wiekowe od 50 do 54 lat",
	"ppr5559": "populacja - procentowe kategorie wiekowe od 55 do 59 lat",
	"ppr6064": "populacja - procentowe kategorie wiekowe od 60 do 64 lat",
	"ppr6569": "populacja - procentowe kategorie wiekowe od 65 do 69 lat",
	"ppr7074": "populacja - procent kategorii wiekowych od 70 do 75 lat",
	"ppr7599": "populacja - procent kategorii wiekowych powyżej 75 lat",
	"poc_tot": "liczba firm prywatnych",
	"workers": "szacunkowa liczba osób pracujących w obszarze",
	"iahu_x": "wskaźnik atrakcyjności - średnia wartość dla obszaru chwytania",
	"iahu_p": "wskaźnik atrakcyjności - wartość dla punktu XY",
	"poi_tot": "liczba punktów POI - ogółem",
	"poi_atm": "liczba punktów POI - bankomat (bankomat)",
	"poi_bank": "liczba punktów POI - oddział banku",
	"poi_mall": "liczba punktów POI - centrum handlowe (centrum handlowe)",
	"poi_eduk": "liczba punktów POI - przedszkole edukacyjne",
	"poi_edup": "liczba punktów POI - edukacja szkoła podstawowa",
	"poi_eduh": "liczba punktów POI - wykształcenie wyższe / uniwersytet",
	"poi_edut": "liczba punktów POI - kategoria edukacji ogółem",
	"poi_edus": "liczba punktów POI - szkoła średnia",
	"poi_ret": "liczba punktów POI - suma detaliczna",
	"poi_rcon": "liczba punktów POI - wygoda sprzedaży",
	"poi_rdro": "liczba punktów POI - drogeria detaliczna (drogeria)",
	"poi_rdys": "liczba punktów POI - sklep dyskontowy detaliczny",
	"poi_rhip": "liczba punktów POI - hipermarket detaliczny",
	"poi_rsup": "liczba punktów POI - supermarket detaliczny",
	"poi_haz": "liczba punktów POI - gry / zagrożenia / lotto",
	"poi_hor": "liczba punktów POI - HoReCa (hotele / restauracje / kawiarnia)",
	"poi_cul": "liczba punktów POI - miejsca kultu (kościół)",
	"poi_poo": "liczba punktów POI - poczta (poczta)",
	"poi_enc": "liczba punktów POI - rozrywka i kult",
	"poi_gst": "liczba punktów POI - stacja benzynowa (stacja paliw)",
	"poi_trst": "liczba punktów POI - stacja kolejowa transportu",
	"poi_trt": "liczba punktów POI - suma transportu",
	"poi_tsto": "liczba punktów POI - przystanki transportu",
	"poi_ps": "liczba punktów POI - biuro / administracja publiczna",
	"poi_hea": "liczba punktów POI - suma zdrowia",
	"poi_heap": "liczba punktów POI - apteka zdrowia",
	"alc_t": "liczba punktów POI - suma alco (sprzedaż detaliczna + horeca)",
	"alc_r": "liczba punktów POI - sklep detaliczny",
	"alc_h": "liczba punktów POI - alco horeca",
	"pod_atm": "distance from nearest POI (-1 = more than 5000m) - bankomat (bankomat)",
	"pod_bank": "distance from nearest POI (-1 = more than 5000m) - oddział banku",
	"pod_mall": "odległość w metrach do najbliższego POI (-1 = większa niż 5000 m) - centrum handlowe (centrum handlowe)",
	"pod_edut": "odległość w metrach do najbliższego POI (-1 = większa niż 5000 m) - kategoria edukacji ogółem",
	"pod_eduk": "distance from nearest POI (-1 = more than 5000m) - przedszkole edukacyjne",
	"pod_edup": "odległość w metrach do najbliższego POI (-1 = więcej niż 5000 m) - szkoła podstawowa edukacji",
	"pod_edus": "odległość w metrach do najbliższego POI (-1 = więcej niż 5000 m) - szkoła średnia edukacyjna",
	"pod_eduh": "odległość w metrach do najbliższego punktu POI (-1 = większa niż 5000 m) - wykształcenie wyższe / uniwersytet",
	"pod_rt": "odległość w metrach do najbliższego POI (-1 = więcej niż 5000 m) - suma detaliczna",
	"pod_rcon": "distance from nearest POI (-1 = more than 5000m) - wygoda sprzedaży detalicznej",
	"pod_rdro": "odległość w metrach do najbliższego POI (-1 = więcej niż 5000 m) - drogeria w sklepie (drogeria)",
	"pod_rdys": "odległość w metrach do najbliższego punktu POI (-1 = większy niż 5000 m) - detaliczny sklep dyskontowy",
	"pod_rhip": "distance from nearest POI (-1 = more than 5000m) - hipermarket handlowy",
	"pod_rsup": "distance from nearest POI (-1 = more than 5000m) - supermarket detaliczny",
	"pod_haz": "distance from nearest POI (-1 = more than 5000m) - gry / hazard / lotto",
	"pod_hor": "odległość w metrach do najbliższego POI (-1 = większa niż 5000 m) - HoReCa (hotele / restauracje / kawiarnia)",
	"pod_cul": "distance from nearest POI (-1 = more than 5000m) - miejsca kultu (kościół)",
	"pod_poo": "odległość w metrach do najbliższego POI (-1 = większa niż 5000 m) - poczta (poczta)",
	"pod_enc": "distance from nearest POI (-1 = more than 5000m) - rozrywka i kult",
	"pod_gst": "odległość w metrach do najbliższego POI (-1 = większe niż 5000 m) - stacja benzynowa (stacja paliw)",
	"pod_trt": "odległość w metrach do najbliższego punktu POI (-1 = większa niż 5000 m) - suma transportu",
	"pod_trst": "distance from nearest POI (-1 = more than 5000m) - stacja kolejowa transportu",
	"pod_tsto": "distance from nearest POI (-1 = more than 5000m) - zatrzymuje się transport",
	"pod_ps": "odległość w metrach do najbliższego POI (-1 = więcej niż 5000 m) - biuro / administracja publiczna",
	"pod_hea": "odległość w metrach do najbliższego POI (-1 = więcej niż 5000 m) - suma zdrowia",
	"pod_heap": "distance from nearest POI (-1 = more than 5000m) - apteka zdrowia",
	"pbne_rb": "procent dominującego typu bloków konstrukcyjnych",
	"pbne_rd": "procent dominującego typu budynku - mieszkalny rozproszony",
	"pbne_rc": "procent dominującego typu budynku - kompakt mieszkaniowy",
	"pbne_fs": "procent dominującego typu budynku - funkcjonalny i serwisowy",
	"pbne_rts": "procent dominującego typu budynku - kamienica / dom segmentowy",
	"pbne_rf": "procent dominującego typu budynku - mieszkalny / funkcjonalny",
	"pbne_rur": "procent dominującego typu budynku - obszar wiejski",
	"plau_for": "procent dominującego użytkowania gruntów - lasy i obszary naturalne",
	"plau_aip": "procent dominującego użytkowania gruntów - lotniska",
	"plau_inc": "procent dominującego użytkowania gruntów - obszary przemysłowe lub handlowe",
	"plau_prz": "procent dominującego użytkowania gruntów - przemysłowy",
	"plau_agr": "procent dominującego użytkowania gruntów - obszary rolnicze",
	"plau_spo": "procent dominującego użytkowania gruntów - tereny sportowe, rekreacyjne, zieleń miejska",
	"plau_ror": "procent dominującego użytkowania gruntów - drogi i koleje",
	"plau_wat": "procent dominującego użytkowania gruntów - woda",
	"plau_cbd": "procent dominującego użytkowania gruntów - rozproszone budynki miejskie",
	"plau_cbc": "procent dominującego użytkowania gruntów - budynki miejskie zwarte",
	"mhh_size": "poziom gminy: średnia liczba osób na gospodarstwo domowe",
	"mpop_den": "poziom gminy: gęstość zaludnienia osób na km2",
	"mpop_axt": "poziom gminy: ludność - średni wiek",
	"mpprf": "poziom gminy: populacja - procent kobiet",
	"mpprm": "poziom gminy: populacja - procent mężczyzn",
	"mppr0004": "poziom gminy: populacja - kategorie wiekowe od 0 do 4 lat",
	"mppr0509": "poziom gminy: populacja - procentowe kategorie wiekowe od 5 do 9 lat",
	"mppr1014": "poziom gminy: populacja - procentowe kategorie wiekowe od 10 do 14 lat",
	"mppr1519": "poziom gminy: populacja - procentowe kategorie wiekowe od 15 do 19 lat",
	"mppr2024": "poziom gminy: populacja - procentowe kategorie wiekowe od 20 do 24 lat",
	"mppr2529": "poziom gminy: populacja - procentowe kategorie wiekowe od 25 do 29 lat",
	"mppr3034": "poziom gminy: populacja - procentowe kategorie wiekowe od 30 do 34 lat",
	"mppr3539": "poziom gminy: populacja - procentowe kategorie wiekowe od 35 do 39 lat",
	"mppr4044": "poziom gminy: populacja - procent kategorii wiekowych od 40 do 44 lat",
	"mppr4549": "poziom gminy: populacja - procentowe kategorie wiekowe od 45 do 49 lat",
	"mppr5054": "poziom gminy: populacja - procentowe kategorie wiekowe od 50 do 54 lat",
	"mppr5559": "poziom gminy: populacja - procent kategorii wiekowych od 55 do 59 lat",
	"mppr6064": "poziom gminy: populacja - procentowe kategorie wiekowe od 60 do 64 lat",
	"mppr6569": "poziom gminy: populacja - procentowe kategorie wiekowe od 65 do 69 lat",
	"mppr7074": "poziom gminy: populacja - procent kategorii wiekowych od 70 do 75 lat",
	"mppr7599": "poziom gminy: populacja - procent kategorii wiekowych od 70 do 75 lat",
	"ewkt": "isoline geometry in WKT (Well Known Text) format",
	"mode": "isoline calculation method",
	"range": "size/radius (meters for distance calculation or seconds for time)",
	"type": "isoline calculation method",
	"catchment_label": "Dane o obszarze",
	"isolines_label": "Izolinie",
	'ctype_MIASTO': 'Miasto',
	'ctype_WIEŚ': 'Wieś',
}

def mapper(shop:dict[str, str]):
	return {MAPPINGS[k]: v for k,v in shop.items() if k in MAPPINGS.keys()}